spring:
  profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/games
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080